---
script: bundle exec rake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq aspell libaspell-dev aspell-en aspell-el aspell-nl

rvm:
  - 1.9
  - 2.0
  - 2.1
  - rbx-2.2
  - jruby

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    email:
      on_success: change
      on_failure: change

cache: bundler

branches:
  only:
    - master
